#!/usr/bin/env node
/**
 * Version Bumping Script
 * Automatically increments version across all necessary files
 * Usage: npm run bump-version [major|minor|patch]
 */

const fs = require('fs');
const path = require('path');

// Version bump type (default: patch)
const bumpType = process.argv[2] || 'patch';

// Files to update
const packageJsonPath = path.join(__dirname, '..', 'package.json');
const gradlePath = path.join(__dirname, '..', 'android', 'app', 'build.gradle');
const capacitorConfigPath = path.join(__dirname, '..', 'capacitor.config.ts');
const versionFilePath = path.join(__dirname, '..', 'src', 'utils', 'version.ts');

// Read current version from package.json
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const currentVersion = packageJson.version;

// Parse version
const [major, minor, patch] = currentVersion.split('.').map(Number);

// Calculate new version
let newVersion;
switch (bumpType) {
  case 'major':
    newVersion = `${major + 1}.0.0`;
    break;
  case 'minor':
    newVersion = `${major}.${minor + 1}.0`;
    break;
  case 'patch':
  default:
    newVersion = `${major}.${minor}.${patch + 1}`;
    break;
}

console.log(`📦 Bumping version: ${currentVersion} → ${newVersion}`);

// Update package.json
packageJson.version = newVersion;
fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n');
console.log('✅ Updated package.json');

// Update Android build.gradle
try {
  let gradle = fs.readFileSync(gradlePath, 'utf8');
  
  // Extract current versionCode
  const versionCodeMatch = gradle.match(/versionCode\s+(\d+)/);
  const currentVersionCode = versionCodeMatch ? parseInt(versionCodeMatch[1]) : 1;
  const newVersionCode = currentVersionCode + 1;
  
  // Update versionCode and versionName
  gradle = gradle.replace(
    /versionCode\s+\d+/,
    `versionCode ${newVersionCode}`
  );
  gradle = gradle.replace(
    /versionName\s+"[^"]+"/,
    `versionName "${newVersion}"`
  );
  
  fs.writeFileSync(gradlePath, gradle);
  console.log(`✅ Updated Android build.gradle (versionCode: ${newVersionCode})`);
} catch (err) {
  console.warn('⚠️  Could not update Android build.gradle:', err.message);
}

// Update iOS project.pbxproj
try {
  const pbxprojPath = path.join(__dirname, '..', 'ios', 'App', 'App.xcodeproj', 'project.pbxproj');
  
  if (fs.existsSync(pbxprojPath)) {
    let pbxproj = fs.readFileSync(pbxprojPath, 'utf8');
    
    // Extract current build number
    const buildNumberMatch = pbxproj.match(/CURRENT_PROJECT_VERSION = (\d+);/);
    const currentBuildNumber = buildNumberMatch ? parseInt(buildNumberMatch[1]) : 1;
    const newBuildNumber = currentBuildNumber + 1;
    
    // Update CURRENT_PROJECT_VERSION (build number)
    pbxproj = pbxproj.replace(
      /CURRENT_PROJECT_VERSION = \d+;/g,
      `CURRENT_PROJECT_VERSION = ${newBuildNumber};`
    );
    
    // Update MARKETING_VERSION (user-facing version)
    pbxproj = pbxproj.replace(
      /MARKETING_VERSION = [^;]+;/g,
      `MARKETING_VERSION = ${newVersion};`
    );
    
    fs.writeFileSync(pbxprojPath, pbxproj);
    console.log(`✅ Updated iOS project.pbxproj (build: ${newBuildNumber})`);
  } else {
    console.warn('⚠️  iOS project.pbxproj not found, skipping...');
  }
} catch (err) {
  console.warn('⚠️  Could not update iOS project.pbxproj:', err.message);
}

// Create/Update version.ts utility file
const versionFileContent = `/**
 * Application Version
 * Auto-generated by scripts/bump-version.js
 * DO NOT EDIT MANUALLY
 */

export const APP_VERSION = '${newVersion}';
export const BUILD_DATE = '${new Date().toISOString()}';
export const PHASE = 'Phase-2';

export const getVersionInfo = () => ({
  version: APP_VERSION,
  buildDate: BUILD_DATE,
  phase: PHASE,
  fullVersion: \`\${PHASE} v\${APP_VERSION}\`
});
`;

// Ensure utils directory exists
const utilsDir = path.join(__dirname, '..', 'src', 'utils');
if (!fs.existsSync(utilsDir)) {
  fs.mkdirSync(utilsDir, { recursive: true });
}

fs.writeFileSync(versionFilePath, versionFileContent);
console.log('✅ Created/Updated src/utils/version.ts');

console.log(`\n🎉 Version bump complete!`);
console.log(`   New version: ${newVersion}`);
console.log(`   Next steps:`);
console.log(`   1. Review changes: git diff`);
console.log(`   2. Build: npm run build:mobile`);
console.log(`   3. Commit: git commit -am "chore: bump version to ${newVersion}"`);

