/**
 * Application Version
 * Auto-generated by scripts/bump-version.js
 * DO NOT EDIT MANUALLY
 */

export const APP_VERSION = '2.0.0';
export const BUILD_DATE = '2026-02-23T09:00:00.000Z';
export const PHASE = 'Phase-2';

export const getVersionInfo = () => ({
  version: APP_VERSION,
  buildDate: BUILD_DATE,
  phase: PHASE,
  fullVersion: `${PHASE} v${APP_VERSION}`
});

export default {
  APP_VERSION,
  BUILD_DATE,
  PHASE,
  getVersionInfo
};
